export type Product = {
  id: string;
  sku: string;
  name: string;
  shortDesc: string;
  fullDesc: string;
  price: number;
  category: "Web Development" | "Software Solutions" | "Maintenance" | "Consulting" | "Design" | "Security";
};

export const products: Product[] = [
  {
    id: "1",
    sku: "ZEN-WEB-001",
    name: "Landing Page Development",
    shortDesc: "High-converting single-page website.",
    fullDesc: "Get a custom-designed, fully responsive landing page optimized for lead generation. Includes basic SEO setup, contact form integration, and fast load speeds.",
    price: 499.00,
    category: "Web Development",
  },
  {
    id: "2",
    sku: "ZEN-WEB-002",
    name: "Corporate Website Package",
    shortDesc: "5-page professional business website.",
    fullDesc: "Establish your online presence with a custom 5-page WordPress site (Home, About, Services, Blog, Contact). Includes mobile optimization and standard security setup.",
    price: 1299.00,
    category: "Web Development",
  },
  {
    id: "3",
    sku: "ZEN-WEB-003",
    name: "E-Commerce Store Setup",
    shortDesc: "Full WooCommerce or Shopify setup.",
    fullDesc: "Launch your online store with up to 50 initial products imported. Includes payment gateway integration, shipping configuration, and a custom storefront design.",
    price: 2499.00,
    category: "Web Development",
  },
  {
    id: "4",
    sku: "ZEN-APP-001",
    name: "Custom Web Application",
    shortDesc: "Tailored web-based software solution.",
    fullDesc: "Build a scalable, custom web app (e.g., portal, dashboard, or SaaS MVP) using React/Node.js. Price represents the initial discovery and architecture phase.",
    price: 4999.00,
    category: "Software Solutions",
  },
  {
    id: "5",
    sku: "ZEN-MNT-001",
    name: "Website Maintenance (Basic)",
    shortDesc: "Monthly core updates and backups.",
    fullDesc: "Ensure your site stays secure. This monthly subscription covers WordPress core/plugin updates, weekly cloud backups, and basic security monitoring.",
    price: 99.00,
    category: "Maintenance",
  },
  {
    id: "6",
    sku: "ZEN-MNT-002",
    name: "Website Maintenance (Pro)",
    shortDesc: "Updates, backups, and 3 hours of dev time.",
    fullDesc: "Comprehensive monthly care for your digital assets. Includes daily backups, uptime monitoring, security sweeps, and 3 hours of dedicated developer support.",
    price: 299.00,
    category: "Maintenance",
  },
  {
    id: "7",
    sku: "ZEN-AUD-001",
    name: "Technical SEO Audit",
    shortDesc: "In-depth website performance analysis.",
    fullDesc: "Identify what is holding your site back. We provide a comprehensive PDF report detailing site speed, code structure errors, indexing issues, and actionable fixes.",
    price: 350.00,
    category: "Consulting",
  },
  {
    id: "8",
    sku: "ZEN-DES-001",
    name: "UI/UX Wireframing",
    shortDesc: "Visual blueprints for your app or site.",
    fullDesc: "Before writing a line of code, we will design low and high-fidelity wireframes mapping out the user journey and interface layout for your digital product.",
    price: 850.00,
    category: "Design",
  },
  {
    id: "9",
    sku: "ZEN-DEV-001",
    name: "API Integration Service",
    shortDesc: "Connect your software to third-party tools.",
    fullDesc: "Streamline your workflow by integrating your existing website or application with third-party APIs (e.g., Salesforce, Stripe, Mailchimp, or custom REST APIs).",
    price: 750.00,
    category: "Web Development",
  },
  {
    id: "10",
    sku: "ZEN-DEV-002",
    name: "Website Migration Service",
    shortDesc: "Seamless host or domain transfer.",
    fullDesc: "Moving to a new server? We handle the complete migration of your website files, databases, and DNS settings with zero data loss and minimal downtime.",
    price: 250.00,
    category: "Web Development",
  },
  {
    id: "11",
    sku: "ZEN-DEV-003",
    name: "Speed Optimization Package",
    shortDesc: "Boost your website's loading speed.",
    fullDesc: "We will minify code, compress images, leverage browser caching, and optimize your database to ensure your site passes Core Web Vitals with flying colors.",
    price: 400.00,
    category: "Web Development",
  },
  {
    id: "12",
    sku: "ZEN-SEC-001",
    name: "Malware Removal & Cleanup",
    shortDesc: "Emergency hacked website recovery.",
    fullDesc: "If your site has been compromised, we will quarantine the server, remove malicious code, restore from a clean backup, and patch vulnerabilities.",
    price: 600.00,
    category: "Security",
  },
  {
    id: "13",
    sku: "ZEN-APP-002",
    name: "Custom API Development",
    shortDesc: "Build a secure API for your data.",
    fullDesc: "We design and develop secure REST or GraphQL APIs to allow your disparate software systems to communicate and share data seamlessly.",
    price: 1500.00,
    category: "Software Solutions",
  },
  {
    id: "14",
    sku: "ZEN-APP-003",
    name: "Database Architecture Design",
    shortDesc: "Scalable database planning.",
    fullDesc: "Lay a solid foundation for your software. We design optimized relational (SQL) or non-relational (NoSQL) database schemas tailored to your application's needs.",
    price: 950.00,
    category: "Software Solutions",
  },
  {
    id: "15",
    sku: "ZEN-CON-001",
    name: "1-on-1 Tech Consultation",
    shortDesc: "60-minute strategy call.",
    fullDesc: "Book a dedicated hour with a senior developer to discuss your software architecture, project feasibility, or to troubleshoot complex technical roadblocks.",
    price: 150.00,
    category: "Consulting",
  },
];